"""Plot SQD alpha-sweep results stored in a pickle file.

This script expects a pickle generated by `first_quant_config_recover.py` with keys:
- first_iter1_mean, first_iter1_std, first_final_mean, first_final_std
- second_iter1_mean, second_iter1_std, second_final_mean, second_final_std

The plot is baseline-shifted so that the recovered-signal mean at alpha=1 is zero:
    <E - E_{alpha=1}>
"""

from __future__ import annotations

import argparse
import pickle
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def _parse_alpha_list(alpha_csv: str | None, *, alpha_min: float, alpha_max: float, alpha_steps: int) -> np.ndarray:
    if alpha_csv is not None:
        parts = [p.strip() for p in alpha_csv.split(",") if p.strip()]
        if not parts:
            raise ValueError("--alphas was provided but no values were parsed")
        alphas = np.asarray([float(p) for p in parts], dtype=float)
    else:
        if alpha_steps < 2:
            raise ValueError("--alpha-steps must be >= 2")
        alphas = np.logspace(np.log10(alpha_min), np.log10(alpha_max), alpha_steps, dtype=float)

    if np.any(alphas < 0.0) or np.any(alphas > 1.0):
        raise ValueError("All alpha values must be in [0, 1]")
    return alphas


def _load_pickle(path: Path) -> dict:
    with path.open("rb") as f:
        payload = pickle.load(f)
    if not isinstance(payload, dict):
        raise TypeError(f"Expected a dict in pickle, got {type(payload)!r}")
    return payload


def _select_quantization_keys(quantization: str) -> tuple[str, str, str, str]:
    if quantization == "first":
        return (
            "first_iter1_mean",
            "first_iter1_std",
            "first_final_mean",
            "first_final_std",
        )
    if quantization == "second":
        return (
            "second_iter1_mean",
            "second_iter1_std",
            "second_final_mean",
            "second_final_std",
        )
    raise ValueError(f"Unsupported quantization: {quantization}")


def _extract_shifted_series(
    payload: dict,
    *,
    quantization: str,
    alphas: np.ndarray,
    n: int = 100,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    iter1_mean_key, iter1_std_key, final_mean_key, final_std_key = _select_quantization_keys(quantization)

    missing = [
        key
        for key in [iter1_mean_key, iter1_std_key, final_mean_key, final_std_key]
        if key not in payload
    ]
    if missing:
        raise KeyError(f"Missing keys in pickle for {quantization}: {missing}")

    noisy_mean = np.asarray(payload[iter1_mean_key], dtype=float)
    noisy_std = np.asarray(payload[iter1_std_key], dtype=float)/np.sqrt(n)
    recovered_mean = np.asarray(payload[final_mean_key], dtype=float)
    recovered_std = np.asarray(payload[final_std_key], dtype=float)/np.sqrt(n)

    n = noisy_mean.shape[0]
    if any(arr.shape[0] != n for arr in (noisy_std, recovered_mean, recovered_std, alphas)):
        raise ValueError(
            f"Length mismatch for {quantization}. "
            f"Got noisy_mean={n}, noisy_std={noisy_std.shape[0]}, "
            f"recovered_mean={recovered_mean.shape[0]}, recovered_std={recovered_std.shape[0]}, "
            f"alphas={alphas.shape[0]}."
        )

    if np.any(np.isclose(alphas, 1.0)):
        alpha1_index = int(np.argmin(np.abs(alphas - 1.0)))
    else:
        alpha1_index = int(np.argmax(alphas))

    baseline = 0
    noisy_shifted = noisy_mean - baseline
    recovered_shifted = recovered_mean - baseline
    return noisy_shifted, noisy_std, recovered_shifted, recovered_std


def _plot_panel(
    ax: plt.Axes,
    *,
    alphas: np.ndarray,
    noisy_shifted: np.ndarray,
    noisy_std: np.ndarray,
    recovered_shifted: np.ndarray,
    recovered_std: np.ndarray,
    title: str,
) -> None:
    ax.fill_between(
        alphas,
        noisy_shifted - noisy_std,
        noisy_shifted + noisy_std,
        color="#1b5e8a",
        alpha=0.22,
        linewidth=0,
        zorder=1,
    )
    ax.fill_between(
        alphas,
        recovered_shifted - recovered_std,
        recovered_shifted + recovered_std,
        color="#b13a3a",
        alpha=0.22,
        linewidth=0,
        zorder=1,
    )

    ax.plot(
        alphas,
        noisy_shifted,
        marker="o",
        linestyle="none",
        markersize=5.5,
        color="#1b5e8a",
        label="noisy signal",
        zorder=3,
    )
    ax.plot(
        alphas,
        recovered_shifted,
        marker="s",
        linestyle="none",
        markersize=5.5,
        color="#b13a3a",
        label="recovered signal",
        zorder=3,
    )

    # ax.axhline(0.0, color="black", linewidth=1.0, linestyle="--")
    ax.set_xscale("log")
    ax.set_ylabel(r"$\langle E - E_{\alpha=1} \rangle$ (Ha)")
    ax.set_title(title)
    ax.grid(True, which="both")
    ax.legend(loc="best")


def _publication_style() -> None:
    plt.rcParams.update(
        {
            "figure.dpi": 150,
            "savefig.dpi": 600,
            "font.family": "serif",
            "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
            "mathtext.fontset": "stix",
            "axes.labelsize": 12,
            "axes.titlesize": 13,
            "axes.linewidth": 1.0,
            "xtick.labelsize": 10,
            "ytick.labelsize": 10,
            "legend.fontsize": 10,
            "legend.frameon": True,
            "legend.framealpha": 0.95,
            "grid.alpha": 0.3,
            "grid.linewidth": 0.6,
        }
    )


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Plot alpha-sweep means/stdev from a pickle with publication-style formatting."
        )
    )
    parser.add_argument("pickle_file", type=Path, help="Path to the alpha-sweep pickle file.")
    parser.add_argument(
        "--quantization",
        choices=["first", "second", "both"],
        default="both",
        help="Which quantization series to plot from the pickle.",
    )
    parser.add_argument(
        "--alphas",
        type=str,
        default=None,
        help="Comma-separated alpha values. If omitted, logspace from alpha-min..alpha-max is used.",
    )
    parser.add_argument("--alpha-min", type=float, default=0.000001)
    parser.add_argument("--alpha-max", type=float, default=1.0)
    parser.add_argument("--alpha-steps", type=int, default=None)
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional output path (e.g. figure.pdf). If omitted, shows interactively.",
    )
    parser.add_argument(
        "--n",
        type=int,
        default=100,
        help="Number of samples used to compute the means/stdevs in the pickle. Used to scale stdev by sqrt(n).",
    )
    args = parser.parse_args(argv)

    payload = _load_pickle(args.pickle_file)

    if args.alpha_steps is None:
        alpha_steps = int(np.asarray(payload["first_iter1_mean"], dtype=float).shape[0])
    else:
        alpha_steps = args.alpha_steps

    if "alphas" in payload:
        alphas = np.asarray(payload["alphas"], dtype=float)
    else:
        alphas = _parse_alpha_list(
            args.alphas,
            alpha_min=args.alpha_min,
            alpha_max=args.alpha_max,
            alpha_steps=alpha_steps,
        )

    _publication_style()

    if args.quantization == "both":
        fig, axs = plt.subplots(2, 1, figsize=(7.2, 8.2), sharex=True, constrained_layout=True)

        first_series = _extract_shifted_series(payload, quantization="first", alphas=alphas, n=args.n)
        _plot_panel(
            axs[0],
            alphas=alphas,
            noisy_shifted=first_series[0],
            noisy_std=first_series[1],
            recovered_shifted=first_series[2],
            recovered_std=first_series[3],
            title="First-quantized SQD signal comparison",
        )

        second_series = _extract_shifted_series(payload, quantization="second", alphas=alphas, n=args.n)
        _plot_panel(
            axs[1],
            alphas=alphas,
            noisy_shifted=second_series[0],
            noisy_std=second_series[1],
            recovered_shifted=second_series[2],
            recovered_std=second_series[3],
            title="Second-quantized SQD signal comparison",
        )
        axs[1].set_xlabel(r"$\alpha$")
    else:
        fig, ax = plt.subplots(figsize=(6.6, 4.5), constrained_layout=True)
        noisy_shifted, noisy_std, recovered_shifted, recovered_std = _extract_shifted_series(
            payload,
            quantization=args.quantization,
            alphas=alphas,
            n=args.n
        )
        _plot_panel(
            ax,
            alphas=alphas,
            noisy_shifted=noisy_shifted,
            noisy_std=noisy_std,
            recovered_shifted=recovered_shifted,
            recovered_std=recovered_std,
            title=f"{args.quantization.capitalize()}-quantized SQD signal comparison",
        )
        ax.set_xlabel(r"$\alpha$")

    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(args.output, bbox_inches="tight")
        print(f"Saved figure to {args.output}")
    else:
        plt.show()


if __name__ == "__main__":
    main()
